# do not check code copied into the project
# do not check testing data
[files]
extend-exclude = [
  "t/sharness.sh",
  "t/t0000-sharness.t",
  "t/data/*",
  "src/common/libccan",
]

[default.extend-words]
# commonly used names/variables that aren't typos
BA = "BA"
HPE = "HPE"
SHS = "SHS"
