coverage:
 round: down
 range: "65...100"
 ignore:
 - "^t/.*"
 - ".*/test/.*"

 # Allow coverage to drop up to 0.1%
 status:
  project:
   default:
    threshold: .1

comment:
 layout: "header, diff, changes, tree"
 behavior: new
 after_n_builds: 2

codecov:
 notify:
  after_n_builds: 2
