#!/bin/sh -e

# Load jobtap plugin, unless it's already loaded (e.g. by config)
jobtap_load() {
    if flux jobtap query $1 >/dev/null 2>&1; then
        echo $1 is already loaded 2>&1
    else
        flux jobtap load $1
    fi
}

if test $(flux getattr rank) -eq 0; then
    jobtap_load cray-pmi-bootstrap.so
fi
