#!/bin/sh -e

if [ $(flux getattr rank) -eq 0 && -n "$FLUX_ENCLOSING_ID" ]; then
    HOSTLIST=$(flux --parent job eventlog -fjson $FLUX_ENCLOSING_ID | \
               jq -r 'select(.name == "exception"
                     and .context.type == "dws-node-failure")
                     | .context.note' | flux hostlist)
    if [ -n "$HOSTLIST" ]; then
        echo draining $HOSTLIST
        flux resource drain $HOSTLIST "missing rabbit file systems"
    fi
fi
